
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-05T14:30:09.259+02:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "creerCompteUtilisateurFault", targetNamespace = "http://www.example.org/UtilisateurService/")
public class CreerCompteUtilisateurFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2124053197896280651L;
	private CreerCompteUtilisateurFault creerCompteUtilisateurFault;

    public CreerCompteUtilisateurFault_Exception() {
        super();
    }

    public CreerCompteUtilisateurFault_Exception(String message) {
        super(message);
    }

    public CreerCompteUtilisateurFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CreerCompteUtilisateurFault_Exception(String message, CreerCompteUtilisateurFault creerCompteUtilisateurFault) {
        super(message);
        this.creerCompteUtilisateurFault = creerCompteUtilisateurFault;
    }

    public CreerCompteUtilisateurFault_Exception(String message, CreerCompteUtilisateurFault creerCompteUtilisateurFault, java.lang.Throwable cause) {
        super(message, cause);
        this.creerCompteUtilisateurFault = creerCompteUtilisateurFault;
    }

    public CreerCompteUtilisateurFault getFaultInfo() {
        return this.creerCompteUtilisateurFault;
    }
}
