
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-21T11:54:24.157+02:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "emprunterEditionFault", targetNamespace = "http://www.example.org/EditionService/")
public class EmprunterEditionFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6917241785899024824L;
	private EmprunterEditionFault emprunterEditionFault;

    public EmprunterEditionFault_Exception() {
        super();
    }

    public EmprunterEditionFault_Exception(String message) {
        super(message);
    }

    public EmprunterEditionFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EmprunterEditionFault_Exception(String message, EmprunterEditionFault emprunterEditionFault) {
        super(message);
        this.emprunterEditionFault = emprunterEditionFault;
    }

    public EmprunterEditionFault_Exception(String message, EmprunterEditionFault emprunterEditionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.emprunterEditionFault = emprunterEditionFault;
    }

    public EmprunterEditionFault getFaultInfo() {
        return this.emprunterEditionFault;
    }
}
