
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-16T09:43:22.353+02:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "gestionPretFault", targetNamespace = "http://www.example.org/EditionService/")
public class GestionPretFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6206136663306443262L;
	private GestionPretFault gestionPretFault;

    public GestionPretFault_Exception() {
        super();
    }

    public GestionPretFault_Exception(String message) {
        super(message);
    }

    public GestionPretFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GestionPretFault_Exception(String message, GestionPretFault gestionPretFault) {
        super(message);
        this.gestionPretFault = gestionPretFault;
    }

    public GestionPretFault_Exception(String message, GestionPretFault gestionPretFault, java.lang.Throwable cause) {
        super(message, cause);
        this.gestionPretFault = gestionPretFault;
    }

    public GestionPretFault getFaultInfo() {
        return this.gestionPretFault;
    }
}
