
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-08-14T09:35:56.423+02:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "rechercheEditionFault", targetNamespace = "http://www.example.org/EditionService/")
public class RechercheEditionFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 3470079987484204092L;
	private RechercheEditionFault rechercheEditionFault;

    public RechercheEditionFault_Exception() {
        super();
    }

    public RechercheEditionFault_Exception(String message) {
        super(message);
    }

    public RechercheEditionFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public RechercheEditionFault_Exception(String message, RechercheEditionFault rechercheEditionFault) {
        super(message);
        this.rechercheEditionFault = rechercheEditionFault;
    }

    public RechercheEditionFault_Exception(String message, RechercheEditionFault rechercheEditionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.rechercheEditionFault = rechercheEditionFault;
    }

    public RechercheEditionFault getFaultInfo() {
        return this.rechercheEditionFault;
    }
}
